development:
  adapter: postgresql
  encoding: unicode
  database: db_development

test:
  adapter: postgresql
  encoding: unicode
  database: db_test

staging:
  adapter: postgresql
  encoding: unicode
  database: db_staging
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  reaping_frequency: 10
  sslmode: prefer

production:
  adapter: postgresql
  encoding: unicode
  database: db_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  reaping_frequency: 10
  sslmode: prefer
